### ISSUE TITLE
Grid column formatting not applied when printing dates

### ISSUE THREAD

**Issue by jpolvora** [loiane/extjs4-ux-gridprinter#24]
When rendering the grid row, format (e.g. date format) is not being taken into account.

```
{ text: 'Data/Hora Entrada', dataIndex: 'DataHoraEntrada', xtype: 'datecolumn', format: 'd/m/Y H:i:s', flex: 1 },
```

The printed result shows m/d/Y default date format.

**Comment by chamacs** [comment]
The actual bug causing the problem is with this line:
`value = column.renderer ? column.renderer.call(grid, value, meta, item, row, col, grid.store, grid.view) : value;`

The first parameter of the column.renderer.call should be column, not grid (for the 'thisArg' of the column renderer).
`value = column.renderer ? column.renderer.call(column, value, meta, item, row, col, grid.store, grid.view) : value;`
